# kang
goserver:
  image: golang:1.7.1
  working_dir: /go/src/message-board
  # command: go run /go/src/message-board/main.go
  command: go run main.go
  volumes:
    - $HOME/go/src/message-board:/go/src/message-board
  ports:
    - 8091:8091
  links:
    - mysql
    - mongodb
mysql:
  image: mysql:5.7
  volumes:
    - $HOME/go/src/message-board/db/mysql:/var/lib/mysql
  ports:
    - 3307:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
mongodb:
  image: mongo:3.2
  command: mongod --smallfiles --quiet --logpath=/dev/null
  volumes:
    - $HOME/go/src/message-board/db/mongo:/data/db
  ports:
    - 27017:27017
#   image: golang:1.7.1
#   working_dir: $GOPATH/src/db-test
#   command: go run /go/src/db-test/main.go
#   volumes:
#     - $GOPATH/src/db-test:/go/src/db-test
#   ports:
#     - 8091:8091
#   links:
#     - mysql
#     - mongodb
# mysql:
#   image: mysql:5.7
#   volumes:
#     - $GOPATH/src/db-test/db/mysql:/var/lib/mysql
#   ports:
#     - 3307:3306
#   environment:
#     MYSQL_ROOT_PASSWORD: root
# mongodb:
#   image: mongo:3.2
#   # volumes:
#   #   - $GOPATH/src/db-test/db/mongo:/data/db
#   ports:
#     - 27017:27017
#   command: mongod --smallfiles --quiet --logpath=/dev/null