goserver:
  image: golang:latest
  working_dir: $GOPATH/src/message-board
  command: go run /go/src/message-board/server/main.go
  environment: 
    USERS_DB_NAME: users_test
  volumes:
    - $GOPATH/src/message-board:/go/src/message-board
  ports:
    - 8091:8091
  links:
    - mysql
    - mongodb
mysql:
  image: mysql:latest
  volumes:
    - $GOPATH/src/message-board/server/db/mysql:/var/lib/mysql
  ports:
    - 3306:3306
  environment: 
    MYSQL_ROOT_PASSWORD: root
mongodb:
  image: mongo:latest
  # volumes: 
  #   - $GOPATH/src/message-board/db/mongo:/var/lib/mongo
  ports: 
    - 27017:27017
  command: mongod --smallfiles --quiet --logpath=/dev/null